### Overview ###
# The values-base.yaml file installs only the necessary components for enabling the New Relic Kubernetes UIs.  These UIs include the Kubernetes Navigator, Cluster Overview dashboard, Kubenetes entity dashboards, and Kubernetes Events page.

### Global Settings ###

# All sub-charts inherit these configuration options.
# See the README for the common library for all available configuration options.
# https://github.com/newrelic/helm-charts/blob/master/library/common-library
global:
  # -- The cluster name for the Kubernetes cluster.
  cluster: "example-cluster"
  # -- Name of the Secret object where the license key is stored
  customSecretName: "new-relic-secret"
  # -- Key in the Secret object where the license key is stored
  customSecretLicenseKey: "new-relic-license-key"

### Sub-Chart Settings ###

# Enables the newrelic-infrastructure chart: https://github.com/newrelic/nri-kubernetes/tree/main/charts/newrelic-infrastructure
# Description: Collects Kubernetes metrics from Kube State Metrics, Kubelet, and cAdvisor from within the cluster. All available configuration options can be found in the newrelic-infrastructure values file.
# Values File URL: https://github.com/newrelic/nri-kubernetes/blob/main/charts/newrelic-infrastructure/values.yaml
newrelic-infrastructure:
  enabled: true

# Enables the Kube State Metrics chart: https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-state-metrics
# Description: Kube State Metrics (KSM) is a simple service that listens to the Kubernetes API server and generates metrics about the state of the objects.  It is a critical component to New Relic's Kubernetes observability offering.
# Additional Notes: This is mandatory if `newrelic-infrastructure.enabled` is set to `true` and the user does not provide its own instance of KSM version >=1.8 and <=2.0. Note, kube-state-metrics v2+ disables labels/annotations metrics by default. You can enable the target labels/annotations metrics to be monitored by using the metricLabelsAllowlist/metricAnnotationsAllowList options described [here](https://github.com/prometheus-community/helm-charts/blob/159cd8e4fb89b8b107dcc100287504bb91bf30e0/charts/kube-state-metrics/values.yaml#L281-L297) in your Kubernetes clusters.
# Values File URL: https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-state-metrics/values.yaml
kube-state-metrics:
  enabled: true

# Enables the nri-kube-events chart: https://github.com/newrelic/nri-kube-events/blob/main/charts/nri-kube-events
# Description: Sends Kubernetes Events from the cluster to New Relic
# Values File URL: https://github.com/newrelic/nri-kube-events/blob/main/charts/nri-kube-events/values.yaml
nri-kube-events:
  enabled: true

# Enables the nri-metadata-injection chart: https://github.com/newrelic/k8s-metadata-injection/tree/main/charts/nri-metadata-injection
# Description: Creates a MutatingAdmissionWebhook that adds New Relic specific ENV vars to newly created Pods in the cluster.  Enables correlation between APM and Infra.
# Values File URL: https://github.com/newrelic/k8s-metadata-injection/blob/main/charts/nri-metadata-injection/values.yaml
nri-metadata-injection:
  enabled: true